services:
  - type: web
    name: requests-api
    runtime: python
    plan: free
    pythonVersion: 3.11

    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
      - key: DB_USER
      - key: DB_PASSWORD
      - key: DB_NAME
      - key: DB_PORT